[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#name = "adventofcode2021"
#path = "src/lib.rs"

[dependencies]
glam = "0.24.2"
itertools = "0.10"
regex = "1.10.2"
